/* 
 * $Id$
 * 
 * Copyright (c) 2012-2021 Stephane GALLAND.
 * 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


options {
  IGNORE_CASE = true;
  STATIC = false;
}

PARSER_BEGIN(BasicParser)

package fr.utbm.info.da53.lw2.parser;

import fr.utbm.info.da53.lw2.error.BasicParserError;
import fr.utbm.info.da53.lw2.error.BasicParserWarning;
import fr.utbm.info.da53.lw2.symbol.SymbolTable;import fr.utbm.info.da53.lw2.type.NumberUtil;
import fr.utbm.info.da53.lw2.syntaxtree.*;

public class BasicParser{
    private int basicLineNumber = 1;
    private final SymbolTable symbolTable = new SymbolTable();

    /** Replies the symbol table used by the parser.
    * @return the symbol table.
    */
    public SymbolTable getSymbolTable() {
        return this.symbolTable;
    }
}}
}

PARSER_END(BasicParser)

SKIP :
{
" "
| "\t"
| "\r"
| "REM (~[\n])*"
}

TOKEN : {
        < CR: "\n" >
    |   < NUMBER: (["0"-"9"])+ ("."(["0"-"9"])+)?>
    |   < STRING: ("\"" (~["\""])* "\"") >
    |   < PRINT: "PRINT" >
    |   < GOTO: "GOTO" >
    |   < GOSUB: "GOSUB" >
    |   < RETURN: "RETURN" >
    |   < INPUT: "INPUT" >
    |   < LET: "LET" >
    |   < END: "END" >
    |   < ELSE: "ELSE" >
    |   < IF: "IF" >
    |   < THEN: "THEN" >
    |   < EQ: "=" >
    |   < DIFF: "<>" >
    |   < LT: "<" >
    |   < GT: ">" >
    |   < LE: "<=" >
    |   < GE: ">=" >
    |   < OPEN_PARENT: "(" >
    |   < CLOSE_PARENT: ")" >
    |   < COMA: "," >
    |   < PLUS: "+" >
    |   < MINUS: "-" >
    |   < MULTIPLY: "*" >
    |   < DIVIDE: "/" >
    |   < IDENTIFIER: (["a"-"z", "A"-"Z"] (["a"-"z", "A"-"Z", "0"-"9"])* ) >
 }

private void code() throws CompilerException:
{}
{
    lineOfCode() restOfCode() {}
}

private void restOfCode() throws CompilerException:
{}
{
  <CR> lineOfCode() restOfCode()  {}
  | {}
}


private void lineOfCode() throws CompilerException:
{
    Token t;
    AbstractStatementTreeNode s;
}
{
  t=<NUMBER> s=statement()
  | s=statement() {}
}


private AbstractStatementTreeNode statement() throws CompilerException:
{
    Token t1, t2, t3;
    AbstractStatementTreeNode s1, s2;
    AbastractComparisonOperatorTreeNode r;
    AbstractValueTreeNode v1, v2;
}
{
    t1=<PRINT> v1=expression()                          {return new PrintStatementTreeNode(v1);}
    |t1=<IF> v1=expression() r=relop() v2=expression() t2=<THEN> s1=statement()  s2=elseStatement() {if(v1 == null || r == null || v2 == null || s1 == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,"Syntax error in IF statement");
                                                                                                        return new IfStatementTreeNode(r, s1, s2);}
    |t1=<GOTO> v1=expression()                        { if(v1 == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,"Syntax error in GOTO statement");
                                                        return new GotoStatementTreeNode(v1);}
    |t1=<INPUT> v1=variable()                          { if(v1 == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,"Syntax error in INPUT statement");
                                                        return new InputStatementTreeNode(v1);}
    |t1=<LET> t2=<IDENTIFIER> t3=<EQ> v2=expression() { if(t2 == null || v2 == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,"Syntax error in LET statement");
                                                        this.symbolTable.declare(t2.image,t2.beginLine);
                                                        return new LetStatementTreeNode(t2.image, v2);}
    |t1=<GOSUB> v1=expression()                         {if(v1 == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,"Syntax error in GOSUB statement");
                                                         return new GosubStatementTreeNode(v1);}
    |t1=<RETURN>                                {return new ReturnStatementTreeNode();}
    |t1=<END>                                   {return new EndStatementTreeNode();}
}

private AbstractStatementTreeNode elseStatement() throws CompilerException:
{
    Token t;
    AbstractStatementTreeNode s;
}
{
    t=<ELSE> s=statement() {}
    |   {}
}

private AbastractComparisonOperatorTreeNode relop() throws CompilerException:
{
 Token t;
}
{
   t=<EQ>
   |t=<DIFF>
   |t=<LT>
   |t=<LE>
   |t=<GT>
   |t=<GE>
}

private AbstractValueTreeNode expression() throws CompilerException:
{
}
{
    term() expressionp()
}


private AbstractValueTreeNode expressionp() throws CompilerException:
{}
{
    <PLUS> term() expressionp()
    |<MINUS> term() expressionp()
    | {}
}

private AbstractValueTreeNode term():
{}
{
    factor() termp()
}

private AbstractValueTreeNode termp(float t) throws CompilerException:
{float e, r;}
{
    <MULTIPLY> e = factor() r = termp(e+t) {return e;}
    |<DIVIDE> factor() termp()
    | {}
}

private AbstractValueTreeNode factor() throws CompilerException:
{Number e;}
{
    <OPEN_PARENT> e = expression() <CLOSE_PARENT> {return e;}
    | e = variable() {return e;}
}

private AbstractValueTreeNode variable() throws CompilerException:
{
        Token t;
}
{
    t = <NUMBER> {return NumberUtil.parse(e.image);}
    | t = <IDENTIFIER> {this.symbolTable.add(t.image,t.beginLine);
                        return this.symbolTable.get(t.image);}
}


