options {
  IGNORE_CASE = true;
  STATIC = false;
}

PARSER_BEGIN(BasicParser)

package fr.utbm.info.da53.lw2.parser;

import java.util.SortedMap;
import java.util.TreeMap;
import fr.utbm.info.da53.lw2.context.*;
import fr.utbm.info.da53.lw2.error.*;
import fr.utbm.info.da53.lw2.syntaxtree.*;
import fr.utbm.info.da53.lw2.syntaxtree.reloop.*;
import fr.utbm.info.da53.lw2.syntaxtree.variable.*;
import fr.utbm.info.da53.lw2.syntaxtree.statements.*;
import fr.utbm.info.da53.lw2.syntaxtree.operator.*;
import fr.utbm.info.da53.lw2.symbol.SymbolTable;
import fr.utbm.info.da53.lw2.type.NumberUtil;

public class BasicParser{
    private Integer basicLineNumber = 1;
    private final SymbolTable symbolTable = new SymbolTable();

    /** Parse the input stream.
     * @return the syntax tree of the program.
    */
    public SortedMap<Integer,Statement> executeCompiler() throws CompilerException,ParseException {
    			SortedMap<Integer,Statement> codeMap = new TreeMap<Integer,Statement>();
    			this.symbolTable.clear();
    			code(codeMap);
    			return codeMap;
    }

    /** Replies the symbol table used by the parser.
    * @return the symbol table.
    */
    public SymbolTable getSymbolTable() {
        return this.symbolTable;
    }
}

PARSER_END(BasicParser)

SKIP :
{
" "
| "\t"
| "\r"
| "REM (~[\n])*"
}

TOKEN : {
        < CR: "\n" >
    |   < NUMBER: (["0"-"9"])+ ("."(["0"-"9"])+)?>
    |   < STRING: ("\"" (~["\""])* "\"") >
    |   < PRINT: "PRINT" >
    |   < GOTO: "GOTO" >
    |   < GOSUB: "GOSUB" >
    |   < RETURN: "RETURN" >
    |   < INPUT: "INPUT" >
    |   < LET: "LET" >
    |   < END: "END" >
    |   < ELSE: "ELSE" >
    |   < IF: "IF" >
    |   < THEN: "THEN" >
    |   < EQ: "=" >
    |   < DIFF: "<>" >
    |   < LT: "<" >
    |   < GT: ">" >
    |   < LE: "<=" >
    |   < GE: ">=" >
    |   < OPEN_PARENT: "(" >
    |   < CLOSE_PARENT: ")" >
    |   < COMA: "," >
    |   < PLUS: "+" >
    |   < MINUS: "-" >
    |   < MULTIPLY: "*" >
    |   < DIVIDE: "/" >
    |   < IDENTIFIER: (["a"-"z", "A"-"Z"] (["a"-"z", "A"-"Z", "0"-"9"])* ) >
 }

private void code(SortedMap<Integer,Statement> codeMap) throws CompilerException:
{}
{
    lineOfCode(codeMap) restOfCode(codeMap) {}
}

private void restOfCode(SortedMap<Integer,Statement> codeMap) throws CompilerException:
{}
{
  <CR> lineOfCode(codeMap) restOfCode(codeMap)  {}
  | {}
}


private void lineOfCode(SortedMap<Integer,Statement> codeMap) throws CompilerException:
{
    Token t;
    AbstractStatementTreeNode s;
}
{
  t=<NUMBER> s=statement() {Integer Line = (Integer) NumberUtil.parse(t.image,t.beginLine);
                            if (Line == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in line of code");
                            if (s!=null){
                                this.basicLineNumber = Line;
                                codeMap.put(basicLineNumber, s);
                                basicLineNumber++;
                            }
                            }
  | s=statement()           {if (s!=null){
                                codeMap.put(basicLineNumber, s);
                                basicLineNumber++;
                            }}
}


private AbstractStatementTreeNode statement() throws CompilerException:
{
    Token t1, t2, t3;
    AbstractStatementTreeNode s1, s2;
    AbstractComparisonOperatorTreeNode r;
    AbstractValueTreeNode v1, v2;
}
{
    t1=<PRINT> v1=expression()                          {return new PrintStatementNode(v1);}
    |t1=<IF> v1=expression() r=relop() v2=expression() t2=<THEN> s1=statement()  s2=elseStatement() {if(v1 == null || r == null || v2 == null || s1 == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in IF statement");
                                                                                                        return new IfStatementNode(r, s1, s2);}
    |t1=<GOTO> v1=expression()                        { if(v1 == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in GOTO statement");
                                                        return new GotoStatementNode(v1);}
    |t1=<LET> t2=<IDENTIFIER> t3=<EQ> v2=expression() { if(t2 == null || v2 == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in LET statement");
                                                        this.symbolTable.declare(t2.image,t2.beginLine);
                                                        return new LetStatementNode(t2.image, v2);}
    |t1=<GOSUB> v1=expression()                         {if(v1 == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in GOSUB statement");
                                                         return new GosubStatementNode(v1);}
    |t1=<RETURN>                                {return new ReturnStatementNode();}
    |t1=<END>                                   {return new EndStatementNode();}
}

private AbstractStatementTreeNode elseStatement() throws CompilerException:
{
    Token t;
    AbstractStatementTreeNode s;
}
{
    t=<ELSE> s=statement() {if (s == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in ELSE statement");
                            return s;}
    |   {return null;}
}

private AbstractComparisonOperatorTreeNode relop() throws CompilerException:
{
 Token t;
}
{
   t=<EQ>       {return new EQNode();}
   |t=<DIFF>    {return new NENode();}
   |t=<LT>      {return new LTNode();}
   |t=<LE>      {return new LENode();}
   |t=<GT>      {return new GTNode();}
   |t=<GE>      {return new GENode();}
}

private AbstractValueTreeNode expression() throws CompilerException:
{
    AbstractValueTreeNode l, r;
}
{
    l=term(null) r=expressionp(l) {if (l == null || r == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in expression");
                              return r;}
}

private AbstractValueTreeNode expressionp(AbstractValueTreeNode leftOp) throws CompilerException:
{
    Token t;
    AbstractValueTreeNode rightOP, result;
}
{
    t=<PLUS> rightOP=term(null)                {if (rightOP == null || leftOp == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in expression");
                                        return new SumNode(leftOp, rightOP);}
    result=expressionp(rightOP)         {return result;}
    |t=<MINUS> rightOP=term(null)               {if (rightOP == null || leftOp == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in expression");
                                        return new SubNode(leftOp, rightOP);}
     result=expressionp(rightOP)        {return result;}
    |                                   {return null;}
}

private AbstractValueTreeNode term(AbstractValueTreeNode leftOp) throws CompilerException:
{
    AbstractValueTreeNode l, r;
}
{
    l=factor() r=termp(leftOp) {if (l == null || leftOp == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in term");
                        return r;}
}

private AbstractValueTreeNode termp(AbstractValueTreeNode leftOp) throws CompilerException:
{
    Token t;
    AbstractValueTreeNode rightOp, r;
}
{
    t=<MULTIPLY> rightOp=factor()         {if (rightOp == null || leftOp == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in term");
                                    return new MultNode(leftOp, rightOp);}
     r=termp(leftOp)                      {return r;}
    |t=<DIVIDE> rightOp=factor()          {if (rightOp == null || leftOp == null) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in term");
                                    return new DivNode(leftOp, rightOp);}
     r=termp(leftOp)                      {return r;}
    |                               {return null;}
}

private AbstractValueTreeNode factor() throws CompilerException:
{
    AbstractValueTreeNode e;
}
{
    <OPEN_PARENT> e=expression() <CLOSE_PARENT> {return e;}
    | e=variable() {return e;}
}

private AbstractValueTreeNode variable() throws CompilerException:
{
        Token t;
}
{
    t=<NUMBER> {return new NumberNode(t.image);}
    | t=<IDENTIFIER> {this.symbolTable.declare(t.image,t.beginLine);
                        return new IdentifierNode(t.image);}
    | t=<STRING> {return new StringNode(t.image);}
}