/* Generated By:JavaCC: Do not edit this line. BasicParser.java */
package fr.utbm.info.da53.lw2.parser;

import java.util.SortedMap;
import java.util.TreeMap;
import fr.utbm.info.da53.lw2.context.*;
import fr.utbm.info.da53.lw2.error.*;
import fr.utbm.info.da53.lw2.syntaxtree.*;
import fr.utbm.info.da53.lw2.syntaxtree.reloop.*;
import fr.utbm.info.da53.lw2.syntaxtree.variable.*;
import fr.utbm.info.da53.lw2.syntaxtree.statements.*;
import fr.utbm.info.da53.lw2.syntaxtree.operator.*;
import fr.utbm.info.da53.lw2.symbol.SymbolTable;
import fr.utbm.info.da53.lw2.type.NumberUtil;

public class BasicParser implements BasicParserConstants {
    private Integer basicLineNumber = 1;
    private final SymbolTable symbolTable = new SymbolTable();

    /** Parse the input stream.
     * @return the syntax tree of the program.
    */
    public SortedMap<Integer,Statement> executeCompiler() throws CompilerException,ParseException {
                        SortedMap<Integer,Statement> codeMap = new TreeMap<Integer,Statement>();
                        this.symbolTable.clear();
                        code(codeMap);
                        return codeMap;
    }

    /** Replies the symbol table used by the parser.
    * @return the symbol table.
    */
    public SymbolTable getSymbolTable() {
        return this.symbolTable;
    }

  final private void code(SortedMap<Integer,Statement> codeMap) throws ParseException, CompilerException {
    lineOfCode(codeMap);
    restOfCode(codeMap);

  }

  final private void restOfCode(SortedMap<Integer,Statement> codeMap) throws ParseException, CompilerException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CR:
      jj_consume_token(CR);
      lineOfCode(codeMap);
      restOfCode(codeMap);

      break;
    default:
      jj_la1[0] = jj_gen;

    }
  }

  final private void lineOfCode(SortedMap<Integer,Statement> codeMap) throws ParseException, CompilerException {
    Token t;
    AbstractStatementTreeNode s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
      t = jj_consume_token(NUMBER);
      s = statement();
                            Integer Line = (Integer) NumberUtil.parse(t.image,t.beginLine);
                            if (Line == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in line of code");}
                            if (s!=null){
                                this.basicLineNumber = Line;
                                codeMap.put(basicLineNumber, s);
                                basicLineNumber++;
                            }
      break;
    case PRINT:
    case GOTO:
    case GOSUB:
    case RETURN:
    case LET:
    case END:
    case IF:
      s = statement();
                             if (s!=null){
                                codeMap.put(basicLineNumber, s);
                                basicLineNumber++;
                            }
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final private AbstractStatementTreeNode statement() throws ParseException, CompilerException {
    Token t1, t2, t3;
    AbstractStatementTreeNode s1, s2;
    AbstractComparisonOperatorTreeNode r;
    AbstractValueTreeNode v1, v2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PRINT:
      t1 = jj_consume_token(PRINT);
      v1 = expression();
                                                         {if (true) return new PrintStatementNode(v1);}
      break;
    case IF:
      t1 = jj_consume_token(IF);
      v1 = expression();
      r = relop();
      v2 = expression();
      t2 = jj_consume_token(THEN);
      s1 = statement();
      s2 = elseStatement();
                                                                                                     if(v1 == null || r == null || v2 == null || s1 == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in IF statement");}
                                                                                                        {if (true) return new IfStatementNode(r, s1, s2);}
      break;
    case GOTO:
      t1 = jj_consume_token(GOTO);
      v1 = expression();
                                                        if(v1 == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in GOTO statement");}
                                                        {if (true) return new GotoStatementNode(v1);}
      break;
    case LET:
      t1 = jj_consume_token(LET);
      t2 = jj_consume_token(IDENTIFIER);
      t3 = jj_consume_token(EQ);
      v2 = expression();
                                                        if(t2 == null || v2 == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in LET statement");}
                                                        this.symbolTable.declare(t2.image,t2.beginLine);
                                                        {if (true) return new LetStatementNode(t2.image, v2);}
      break;
    case GOSUB:
      t1 = jj_consume_token(GOSUB);
      v1 = expression();
                                                         if(v1 == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in GOSUB statement");}
                                                         {if (true) return new GosubStatementNode(v1);}
      break;
    case RETURN:
      t1 = jj_consume_token(RETURN);
                                                 {if (true) return new ReturnStatementNode();}
      break;
    case END:
      t1 = jj_consume_token(END);
                                                 {if (true) return new EndStatementNode();}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private AbstractStatementTreeNode elseStatement() throws ParseException, CompilerException {
    Token t;
    AbstractStatementTreeNode s;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      t = jj_consume_token(ELSE);
      s = statement();
                            if (s == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in ELSE statement");}
                            {if (true) return s;}
      break;
    default:
      jj_la1[3] = jj_gen;
         {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  final private AbstractComparisonOperatorTreeNode relop() throws ParseException, CompilerException {
 Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
      t = jj_consume_token(EQ);
                 {if (true) return new EQNode();}
      break;
    case DIFF:
      t = jj_consume_token(DIFF);
                 {if (true) return new NENode();}
      break;
    case LT:
      t = jj_consume_token(LT);
                 {if (true) return new LTNode();}
      break;
    case LE:
      t = jj_consume_token(LE);
                 {if (true) return new LENode();}
      break;
    case GT:
      t = jj_consume_token(GT);
                 {if (true) return new GTNode();}
      break;
    case GE:
      t = jj_consume_token(GE);
                 {if (true) return new GENode();}
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private AbstractValueTreeNode expression() throws ParseException, CompilerException {
    AbstractValueTreeNode l, r;
    l = term(null);
    r = expressionp(l);
                                   if (l == null || r == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in expression");}
                              {if (true) return r;}
    throw new Error("Missing return statement in function");
  }

  final private AbstractValueTreeNode expressionp(AbstractValueTreeNode leftOp) throws ParseException, CompilerException {
    Token t;
    AbstractValueTreeNode rightOP, result;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PLUS:
      t = jj_consume_token(PLUS);
      rightOP = term(null);
                                                if (rightOP == null || leftOp == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in expression");}
                                        {if (true) return new SumNode(leftOp, rightOP);}
      result = expressionp(rightOP);
                                         {if (true) return result;}
      break;
    case MINUS:
      t = jj_consume_token(MINUS);
      rightOP = term(null);
                                                 if (rightOP == null || leftOp == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in expression");}
                                        {if (true) return new SubNode(leftOp, rightOP);}
      result = expressionp(rightOP);
                                         {if (true) return result;}
      break;
    default:
      jj_la1[5] = jj_gen;
                                         {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  final private AbstractValueTreeNode term(AbstractValueTreeNode leftOp) throws ParseException, CompilerException {
    AbstractValueTreeNode l, r;
    l = factor();
    r = termp(leftOp);
                                if (l == null || leftOp == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in term");}
                        {if (true) return r;}
    throw new Error("Missing return statement in function");
  }

  final private AbstractValueTreeNode termp(AbstractValueTreeNode leftOp) throws ParseException, CompilerException {
    Token t;
    AbstractValueTreeNode rightOp, r;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MULTIPLY:
      t = jj_consume_token(MULTIPLY);
      rightOp = factor();
                                           if (rightOp == null || leftOp == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in term");}
                                    {if (true) return new MultNode(leftOp, rightOp);}
      r = termp(leftOp);
                                           {if (true) return r;}
      break;
    case DIVIDE:
      t = jj_consume_token(DIVIDE);
      rightOp = factor();
                                           if (rightOp == null || leftOp == null) {if (true) throw new CompilerException(CompilationErrorType.SYNTAX_ERROR,this.basicLineNumber,"Syntax error in term");}
                                    {if (true) return new DivNode(leftOp, rightOp);}
      r = termp(leftOp);
                                           {if (true) return r;}
      break;
    default:
      jj_la1[6] = jj_gen;
                                     {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  final private AbstractValueTreeNode factor() throws ParseException, CompilerException {
    AbstractValueTreeNode e;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OPEN_PARENT:
      jj_consume_token(OPEN_PARENT);
      e = expression();
      jj_consume_token(CLOSE_PARENT);
                                                 {if (true) return e;}
      break;
    case NUMBER:
    case STRING:
    case IDENTIFIER:
      e = variable();
                    {if (true) return e;}
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private AbstractValueTreeNode variable() throws ParseException, CompilerException {
        Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUMBER:
      t = jj_consume_token(NUMBER);
                {if (true) return new NumberNode(t.image);}
      break;
    case IDENTIFIER:
      t = jj_consume_token(IDENTIFIER);
                      this.symbolTable.declare(t.image,t.beginLine);
                        {if (true) return new IdentifierNode(t.image);}
      break;
    case STRING:
      t = jj_consume_token(STRING);
                  {if (true) return new StringNode(t.image);}
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public BasicParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[9];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x20,0x16f40,0x16f00,0x8000,0xfc0000,0x18000000,0x60000000,0x810000c0,0x800000c0,};
   }

  /** Constructor with InputStream. */
  public BasicParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public BasicParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new BasicParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public BasicParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new BasicParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public BasicParser(BasicParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(BasicParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[32];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 9; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 32; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
